services:
  - type: web
    name: pcos-risk-assessment-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    disk:
      name: model-storage
      mountPath: /opt/render/project/src
      sizeGB: 1 